# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test on pull request

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: install yarn
        run: npm install yarn -g
      - name: install packages
        run: yarn install
      - name: build
        run: yarn build
      - name: test
        run: yarn test -u
        env:
          CI: true
